version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: modernsoftwareconcepts
      POSTGRES_DB: admissions
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
